version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sample-backend-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ino35x4vpuye"
s3_prefix = "sample-backend-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
